version: '2'

services:
    mysql:
        container_name: ${APP_NAME}_mysql
        image: mysql/mysql-server
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
    php:
        container_name: ${APP_NAME}_php
        build: php
        ports:
            - 9000:9000
        links:
            - mysql:mysql
        volumes:
            - ${APP_DIR}:/var/www/app
    nginx:
        container_name: ${APP_NAME}_nginx
        build: nginx
        ports:
            - ${APP_PORT}:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ${DATA_DIR}/logs/nginx/:/var/log/nginx

volumes:
    mysql_data:
        ~